{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "1. ошибки можно ловить внутри потока\n",
    "2. можно ловить в вызыващем потоке, в отличие от трединга это сделать проще, и через фьючер, и через эуэйт\n",
    "3. если исключение не пронблюдали, то есть результат не был взят, то оно просто проглатывается, та корутина, которая выбросила исключение, прекращает исполнение, но приложение также не убивается\n",
    "4. await пробрасывает исключение, то есть если из корутины выскочило исключение,и мы сделали await на этой корутине, то await пробросит исключение, и приложение умрет\n",
    "5. future.result() тоже пробрасывает исключение, если резалт взяли в мейнтреде, то приложение тоже умирает\n",
    "6. async for тоже пробрасывает исключение прям сразу, внутрь цикла мы не попадем, то есть надо оборачивать сам async for в трай эксепт, чтобы это исключение отловить\n",
    "7. колбэк - это некая ф-я, которая будет вызвана после завершение таска, как фьючер перейдет в состояние ДАН, навешивается он с помощью add_done_callback(), если же мы в колбэке запрашиваем результат, и он выбрасывает исключение, а мы его не обрабатываем, то приложение не убивается\n",
    "8. gather(return_exceptions=True) позволяет взять результаты из успешно завершенных задач иполучить список исключений и проваленных, \n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
